[2025-03-26T13:41:30.920+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:41:30.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:41:30.930+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:30.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:41:31.012+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:31.006+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:41:31.036+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:41:32.365+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.363+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:execute_launch_script
[2025-03-26T13:41:32.408+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.406+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:execute_launch_script
[2025-03-26T13:41:32.431+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.431+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:execute_launch_script
[2025-03-26T13:41:32.452+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.451+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:execute_launch_script
[2025-03-26T13:41:32.487+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.486+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:execute_launch_script
[2025-03-26T13:41:32.516+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.515+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:execute_launch_script
[2025-03-26T13:41:32.546+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.545+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:execute_launch_script
[2025-03-26T13:41:32.548+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.548+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:41:32.616+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.615+0000] {dag.py:3262} INFO - Creating ORM DAG for execute_launch_script
[2025-03-26T13:41:32.618+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:41:32.618+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:41:32.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 1.820 seconds
[2025-03-26T13:42:03.394+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:03.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:42:03.407+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:03.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:03.475+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:03.467+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:42:03.483+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:03.556+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:03.556+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:42:03.608+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:03.607+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:42:03.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.292 seconds
[2025-03-26T13:42:34.357+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:34.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:42:34.365+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:34.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:34.415+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:34.413+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:42:34.429+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:42:34.519+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:34.518+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:42:34.571+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:42:34.570+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:42:34.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.280 seconds
[2025-03-26T13:43:05.124+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:05.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:43:05.134+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:05.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:05.182+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:05.176+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:43:05.195+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:05.285+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:05.284+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:43:05.337+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:05.336+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:43:05.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.312 seconds
[2025-03-26T13:43:36.095+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:36.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:43:36.112+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:36.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:36.157+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:36.154+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:43:36.166+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:43:36.259+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:36.258+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:43:36.312+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:43:36.311+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:43:36.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.307 seconds
[2025-03-26T13:44:06.753+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:06.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:44:06.789+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:06.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:07.074+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:07.071+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:44:07.106+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:07.280+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:07.279+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:44:07.378+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:07.377+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:44:07.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.926 seconds
[2025-03-26T13:44:38.040+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:38.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:44:38.058+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:38.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:38.125+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:38.119+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:44:38.138+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:44:38.236+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:38.235+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:44:38.294+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:44:38.293+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:44:38.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.362 seconds
[2025-03-26T13:45:08.716+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:08.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:45:08.726+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:08.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:08.775+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:08.773+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:45:08.784+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:08.869+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:08.868+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:45:08.931+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:08.930+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:45:08.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.298 seconds
[2025-03-26T13:45:39.781+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:39.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:45:39.796+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:39.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:39.873+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:39.871+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:45:39.895+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:45:40.033+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:40.033+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:45:40.094+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:45:40.093+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:45:40.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.477 seconds
[2025-03-26T13:46:10.912+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:10.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:46:10.920+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:10.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:10.964+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:10.962+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:46:10.971+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:11.036+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:11.035+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:46:11.071+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:11.070+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:46:11.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.218 seconds
[2025-03-26T13:46:41.876+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:41.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:46:41.888+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:41.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:41.952+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:41.950+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:46:41.961+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:46:42.080+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:42.080+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:46:42.150+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:46:42.150+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:46:42.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.422 seconds
[2025-03-26T13:47:12.498+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:12.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:47:12.507+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:12.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:12.562+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:12.560+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:47:12.573+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:12.661+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:12.660+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:47:12.703+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:12.702+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:47:12.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.278 seconds
[2025-03-26T13:47:43.202+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:43.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:47:43.209+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:43.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:43.244+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:43.242+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:47:43.251+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:47:43.307+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:43.306+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:47:43.351+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:47:43.350+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:47:43.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.213 seconds
[2025-03-26T13:48:14.019+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:14.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:48:14.027+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:14.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:14.069+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:14.066+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:48:14.077+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:14.141+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:14.141+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:48:14.182+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:14.181+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:48:14.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.255 seconds
[2025-03-26T13:48:44.771+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:44.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:48:44.790+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:44.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:44.847+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:44.844+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:48:44.857+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:48:44.926+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:44.925+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:48:44.972+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:48:44.972+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:48:45.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.273 seconds
[2025-03-26T13:49:15.699+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:15.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:49:15.708+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:15.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:15.753+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:15.750+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:49:15.762+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:15.835+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:15.834+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:49:15.887+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:15.886+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:49:15.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.279 seconds
[2025-03-26T13:49:46.380+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:46.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:49:46.403+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:46.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:46.545+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:46.542+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:49:46.558+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:49:46.689+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:46.688+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:49:46.811+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:49:46.810+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:49:46.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.597 seconds
[2025-03-26T13:50:17.212+0000] {processor.py:186} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:17.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:50:17.231+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:17.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:17.308+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:17.305+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:50:17.324+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:17.436+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:17.435+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:50:17.508+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:17.507+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:50:17.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.423 seconds
[2025-03-26T13:50:48.654+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:48.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:50:48.673+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:48.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:48.721+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:48.718+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:50:48.729+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:50:48.827+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:48.826+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:50:48.891+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:50:48.890+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:50:48.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.331 seconds
[2025-03-26T13:51:19.609+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:19.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:51:19.620+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:19.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:19.678+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:19.676+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:51:19.691+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:19.776+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:19.776+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:51:19.828+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:19.828+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:51:19.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.299 seconds
[2025-03-26T13:51:50.369+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:50.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:51:50.388+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:50.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:50.432+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:50.429+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:51:50.440+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:51:50.512+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:50.511+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:51:50.573+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:51:50.572+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:51:50.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.271 seconds
[2025-03-26T13:52:20.953+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:20.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:52:20.963+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:20.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:21.037+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:21.033+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:52:21.044+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:21.160+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:21.160+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:52:21.241+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:21.240+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:52:21.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.474 seconds
[2025-03-26T13:52:51.817+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:51.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:52:51.839+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:51.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:52.421+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:52.417+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:52:52.662+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:52:53.182+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:53.181+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:52:53.403+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:52:53.402+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:52:53.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 1.873 seconds
[2025-03-26T13:57:41.437+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:57:41.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:57:41.461+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:57:41.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:57:41.657+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:57:41.647+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:57:41.719+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:57:41.985+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:57:41.984+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:57:42.075+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:57:42.074+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:57:42.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.796 seconds
[2025-03-26T13:58:12.639+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:12.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:58:12.675+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:12.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:12.849+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:12.827+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:58:12.874+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:13.119+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:13.118+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:58:13.255+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:13.254+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:58:13.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.840 seconds
[2025-03-26T13:58:44.332+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:44.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:58:44.368+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:44.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:44.754+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:44.739+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:58:44.823+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:58:45.076+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:45.075+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:58:45.201+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:58:45.201+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:58:45.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 1.325 seconds
[2025-03-26T13:59:16.185+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:16.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:59:16.218+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:16.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:16.367+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:16.357+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:59:16.407+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:16.654+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:16.653+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:59:16.806+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:16.804+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:59:17.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.918 seconds
[2025-03-26T13:59:48.405+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:48.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T13:59:48.429+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:48.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:48.666+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:48.663+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T13:59:48.699+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T13:59:48.874+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:48.873+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T13:59:48.934+0000] {logging_mixin.py:190} INFO - [2025-03-26T13:59:48.934+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T13:59:49.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.803 seconds
[2025-03-26T14:00:19.624+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:19.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:00:19.647+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:19.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:19.853+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:19.841+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:00:19.885+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:20.056+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:20.055+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:00:20.172+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:20.172+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:00:20.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.725 seconds
[2025-03-26T14:00:50.650+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:50.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:00:50.669+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:50.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:50.769+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:50.767+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:00:50.789+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:00:50.901+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:50.900+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:00:50.971+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:00:50.970+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:00:51.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.434 seconds
[2025-03-26T14:01:21.849+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:21.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:01:21.866+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:21.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:21.981+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:21.969+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:01:22.000+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:22.107+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:22.106+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:01:22.156+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:22.156+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:01:22.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.392 seconds
[2025-03-26T14:01:53.256+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:53.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:01:53.281+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:53.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:53.536+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:53.533+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:01:53.570+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:01:53.673+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:53.673+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:01:53.735+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:01:53.734+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:01:53.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.700 seconds
[2025-03-26T14:02:23.969+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:23.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:02:23.978+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:23.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:24.029+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:24.024+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:02:24.037+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:24.121+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:24.121+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:02:24.183+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:24.182+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:02:24.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.272 seconds
[2025-03-26T14:02:54.843+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:54.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:02:54.863+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:54.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:54.927+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:54.924+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:02:54.937+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:02:55.088+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:55.088+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:02:55.220+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:02:55.219+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:02:55.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.516 seconds
[2025-03-26T14:03:25.928+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:25.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:03:25.938+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:25.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:25.990+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:25.987+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:03:26.001+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:26.078+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:26.077+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:03:26.135+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:26.134+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:03:26.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.292 seconds
[2025-03-26T14:03:56.821+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:56.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:03:56.834+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:56.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:56.893+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:56.885+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:03:56.905+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:03:56.996+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:56.995+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:03:57.069+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:03:57.068+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:03:57.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.392 seconds
[2025-03-26T14:04:27.833+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:27.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:04:27.843+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:27.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:27.907+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:27.902+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:04:27.916+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:28.024+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:28.023+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:04:28.088+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:28.085+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:04:28.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.338 seconds
[2025-03-26T14:04:58.754+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:58.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:04:58.772+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:58.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:58.885+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:58.882+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:04:58.898+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:04:58.996+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:58.995+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:04:59.065+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:04:59.064+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:04:59.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.427 seconds
[2025-03-26T14:05:29.943+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:05:29.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:05:29.952+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:05:29.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:05:30.005+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:05:30.002+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:05:30.016+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:05:30.096+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:05:30.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:05:30.168+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:05:30.168+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:05:30.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.301 seconds
[2025-03-26T14:06:00.812+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:00.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:06:00.832+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:00.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:00.877+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:00.875+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:06:00.886+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:00.961+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:00.960+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:06:01.036+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:01.036+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:06:01.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.341 seconds
[2025-03-26T14:06:31.789+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:31.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:06:31.798+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:31.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:31.837+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:31.834+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:06:31.844+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:06:31.906+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:31.905+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:06:31.944+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:06:31.943+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:06:31.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.222 seconds
[2025-03-26T14:07:56.633+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:07:56.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:07:56.657+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:07:56.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:07:56.751+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:07:56.747+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:07:56.763+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:07:56.856+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:07:56.855+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:07:56.914+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:07:56.913+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:07:56.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.387 seconds
[2025-03-26T14:08:27.682+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:27.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:08:27.699+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:27.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:27.772+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:27.769+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:08:27.805+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:27.924+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:27.924+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:08:28.023+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:28.022+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:08:28.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.479 seconds
[2025-03-26T14:08:58.375+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:58.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:08:58.384+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:58.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:58.447+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:58.444+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:08:58.455+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:08:58.530+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:58.529+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:08:58.576+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:08:58.576+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:08:58.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.278 seconds
[2025-03-26T14:09:29.405+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:09:29.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:09:29.415+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:09:29.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:09:29.532+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:09:29.526+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:09:29.546+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:09:29.672+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:09:29.671+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:09:29.731+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:09:29.730+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:09:29.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.428 seconds
[2025-03-26T14:10:00.629+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:00.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:10:00.638+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:00.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:00.727+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:00.718+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:10:00.740+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:00.837+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:00.837+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:10:00.908+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:00.907+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:10:00.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.386 seconds
[2025-03-26T14:10:31.345+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:31.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:10:31.392+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:31.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:31.568+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:31.554+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:10:31.586+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:10:31.737+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:31.737+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:10:31.802+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:10:31.801+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:10:31.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.606 seconds
[2025-03-26T14:11:02.262+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:02.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:11:02.271+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:02.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:02.323+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:02.321+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:11:02.331+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:02.406+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:02.405+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:11:02.451+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:02.451+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:11:02.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.294 seconds
[2025-03-26T14:11:33.454+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:33.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:11:33.466+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:33.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:33.526+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:33.522+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:11:33.541+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:11:33.665+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:33.665+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:11:33.715+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:11:33.715+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:11:33.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.335 seconds
[2025-03-26T14:12:04.514+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:04.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:12:04.527+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:04.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:04.627+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:04.624+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:12:04.638+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:04.745+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:04.744+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:12:04.808+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:04.807+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:12:04.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.399 seconds
[2025-03-26T14:12:35.557+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:35.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:12:35.568+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:35.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:35.631+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:35.627+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:12:35.640+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:12:35.726+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:35.725+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:12:35.768+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:12:35.768+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:12:35.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.283 seconds
[2025-03-26T14:13:06.045+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:13:06.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:13:06.097+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:13:06.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:13:06.211+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:13:06.208+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:13:06.228+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:13:06.365+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:13:06.364+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:13:06.491+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:13:06.491+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:13:06.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.619 seconds
[2025-03-26T14:16:22.767+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:22.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:16:22.775+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:22.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:22.843+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:22.840+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:16:22.859+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:22.971+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:22.970+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:16:23.013+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:23.012+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:16:23.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.322 seconds
[2025-03-26T14:16:53.588+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:53.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:16:53.593+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:53.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:53.626+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:53.624+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:16:53.631+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:16:53.684+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:53.683+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:16:53.722+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:16:53.722+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:16:53.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.203 seconds
[2025-03-26T14:17:24.365+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:24.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:17:24.374+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:24.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:24.424+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:24.421+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:17:24.434+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:24.517+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:24.517+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:17:24.586+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:24.586+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:17:24.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.297 seconds
[2025-03-26T14:17:55.153+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:55.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:17:55.168+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:55.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:55.278+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:55.276+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:17:55.289+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:17:55.350+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:55.349+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:17:55.400+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:17:55.400+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:17:55.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.315 seconds
[2025-03-26T14:18:25.981+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:25.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:18:25.988+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:25.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:26.027+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:26.025+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:18:26.037+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:26.114+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:26.111+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:18:26.191+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:26.190+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:18:26.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.308 seconds
[2025-03-26T14:18:56.978+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:56.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:18:56.994+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:56.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:57.074+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:57.071+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:18:57.092+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:18:57.205+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:57.205+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:18:57.269+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:18:57.265+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:18:57.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.499 seconds
[2025-03-26T14:19:28.103+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:28.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:19:28.113+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:28.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:28.157+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:28.154+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:19:28.167+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:28.250+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:28.250+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:19:28.348+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:28.347+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:19:28.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.323 seconds
[2025-03-26T14:19:59.010+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:59.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:19:59.019+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:59.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:59.058+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:59.056+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:19:59.065+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:19:59.128+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:59.127+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:19:59.194+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:19:59.194+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:19:59.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.257 seconds
[2025-03-26T14:20:30.002+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:20:30.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:20:30.024+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:20:30.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:20:30.078+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:20:30.075+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:20:30.097+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:20:30.218+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:20:30.217+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:20:30.301+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:20:30.300+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:20:30.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.453 seconds
[2025-03-26T14:24:55.040+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:24:55.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:24:55.048+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:24:55.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:24:55.105+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:24:55.100+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:24:55.121+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:24:55.233+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:24:55.233+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:24:55.281+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:24:55.280+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:24:55.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.328 seconds
[2025-03-26T14:25:25.950+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:25.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:25:25.958+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:25.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:26.018+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:26.015+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:25:26.035+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:26.132+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:26.131+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:25:26.196+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:26.196+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:25:26.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.335 seconds
[2025-03-26T14:25:56.873+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:56.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:25:56.881+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:56.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:56.928+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:56.925+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:25:56.935+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:25:57.022+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:57.021+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:25:57.083+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:25:57.083+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:25:57.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.294 seconds
[2025-03-26T14:26:27.305+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:27.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:26:27.314+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:27.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:27.367+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:27.359+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:26:27.381+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:27.505+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:27.504+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:26:27.557+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:27.556+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:26:27.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.327 seconds
[2025-03-26T14:26:58.098+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:58.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:26:58.113+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:58.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:58.247+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:58.244+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:26:58.273+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:26:58.423+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:58.422+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:26:58.545+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:26:58.544+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:26:58.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.695 seconds
[2025-03-26T14:27:28.857+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:27:28.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:27:28.867+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:27:28.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:27:28.909+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:27:28.907+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:27:28.917+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:27:28.971+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:27:28.970+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:27:29.000+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:27:29.000+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:27:29.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.205 seconds
[2025-03-26T14:27:59.891+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:27:59.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:27:59.912+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:27:59.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:28:00.050+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:00.047+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:28:00.081+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:28:00.210+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:00.209+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:28:00.300+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:00.299+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:28:00.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.684 seconds
[2025-03-26T14:28:30.667+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:28:30.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:28:30.673+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:30.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:28:30.706+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:30.704+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:28:30.713+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:28:30.767+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:30.767+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:28:30.801+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:28:30.801+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:28:30.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.190 seconds
[2025-03-26T14:29:01.531+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:01.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:29:01.541+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:01.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:01.595+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:01.592+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:29:01.605+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:01.683+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:01.682+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:29:01.750+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:01.750+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:29:01.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.280 seconds
[2025-03-26T14:29:32.438+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:32.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:29:32.450+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:32.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:32.489+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:32.487+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:29:32.494+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:29:32.554+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:32.553+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:29:32.591+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:29:32.590+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:29:32.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.227 seconds
[2025-03-26T14:30:03.453+0000] {processor.py:186} INFO - Started process (PID=336) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:03.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:30:03.464+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:03.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:03.512+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:03.510+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:30:03.520+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:03.593+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:03.592+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:30:03.636+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:03.635+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:30:03.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.248 seconds
[2025-03-26T14:30:34.442+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:34.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:30:34.453+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:34.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:34.511+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:34.509+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:30:34.519+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:30:34.589+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:34.589+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:30:34.638+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:30:34.637+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:30:34.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.284 seconds
[2025-03-26T14:31:05.420+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:05.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:31:05.445+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:05.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:05.546+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:05.540+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:31:05.581+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:05.693+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:05.692+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:31:05.750+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:05.749+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:31:05.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.429 seconds
[2025-03-26T14:31:36.699+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:36.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:31:36.714+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:36.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:36.785+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:36.770+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:31:36.800+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:31:37.037+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:37.036+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:31:37.146+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:31:37.145+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:31:37.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.632 seconds
[2025-03-26T14:32:07.556+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:07.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:32:07.564+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:07.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:07.604+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:07.602+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:32:07.612+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:07.693+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:07.692+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:32:07.743+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:07.742+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:32:07.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.308 seconds
[2025-03-26T14:32:38.033+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:38.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:32:38.051+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:38.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:38.116+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:38.113+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:32:38.131+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:32:38.245+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:38.244+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:32:38.287+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:32:38.286+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:32:38.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.345 seconds
[2025-03-26T14:33:08.806+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:08.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:33:08.838+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:08.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:08.936+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:08.932+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:33:08.951+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:09.105+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:09.100+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:33:09.213+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:09.212+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:33:09.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.536 seconds
[2025-03-26T14:33:40.159+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:40.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:33:40.173+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:40.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:40.286+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:40.283+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:33:40.299+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:33:40.409+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:40.407+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:33:40.467+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:33:40.466+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:33:40.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.392 seconds
[2025-03-26T14:34:11.124+0000] {processor.py:186} INFO - Started process (PID=458) to work on /opt/airflow/dags/dag_launch.py
[2025-03-26T14:34:11.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2025-03-26T14:34:11.133+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:34:11.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:34:11.172+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:34:11.170+0000] {templater.py:94} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/app/talend/jobs/CorrigeAge/launch.sh' not found in search path: '/opt/airflow/dags'
[2025-03-26T14:34:11.181+0000] {processor.py:925} INFO - DAG(s) 'execute_launch_script' retrieved from /opt/airflow/dags/dag_launch.py
[2025-03-26T14:34:11.250+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:34:11.249+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-26T14:34:11.293+0000] {logging_mixin.py:190} INFO - [2025-03-26T14:34:11.293+0000] {dag.py:4180} INFO - Setting next_dagrun for execute_launch_script to None, run_after=None
[2025-03-26T14:34:11.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.246 seconds
